name: 'Seasons Greetings 2'
on:
  workflow_dispatch:
    inputs:
      person:
        description: 'Name of the person to send the greeting to'
        required: true
      phone:
        description: 'Phone number to send the greeting to'
      context:
        description: 'Context to use for the greeting'
        required: true
    
jobs:
  send-greeting:
    name: 'Send greeting'
    runs-on: ubuntu-latest
    steps:          
      - name: 'Generate Greeting'
        id: generate
        uses: malantin/ai-seasons-greeting-action@v0.4
        with:
          prompt: '${{ github.event.inputs.person }}, ${{ github.event.inputs.context }}'
          api-key: ${{ secrets.AI_API_KEY }}
          endpoint: ${{ vars.AI_ENDPOINT }}
      - name: 'Send SMS'
        id: send
        uses: twilio-labs/actions-sms@v1
        with:
          fromPhoneNumber: ${{ secrets.TWILIO_PHONE_NUMBER }}
          toPhoneNumber: ${{ secrets.RECEIVER_PHONE_NUMBER_2 }}
          message: ${{ steps.generate.outputs.seasons-greeting }}
        env:
          TWILIO_ACCOUNT_SID: ${{ vars.TWILIO_ACCOUNT_SID }}
          TWILIO_API_KEY: ${{ secrets.TWILIO_API_KEY }}
          TWILIO_API_SECRET: ${{ secrets.TWILIO_API_SECRET }}
